const user = require("../../user/index");
const products = require("../../products/");
const scripts = require("../../scripts");
const looks = require("../../looks");
const coupons = require("../../coupon");
const pools = require("../../pools");
const xrpPayment = require("../../xrp-payment");
const nfts = require("../../nfts");
const transferNft = require("../../transfer-nft");
const badgeNft = require("../../badge-nft");
const getOrders = require("../../orders");
const customerWallet = require("../../customers-wallet");
const sendMail = require("../../send-mail");
const nftStore = require("../../nft-store");
const islmTransaction = require("../../islm-transaction");

user.initRoutes();
products.initRoutes();
scripts.initRoutes();
looks.initRoutes();
coupons.initRoutes();
pools.initRoutes();
xrpPayment.initRoutes();
nfts.initRoutes();
transferNft.initRoutes();
badgeNft.initRoutes();
getOrders.initRoutes();
customerWallet.initRoutes();
sendMail.initRoutes();
nftStore.initRoutes();
islmTransaction.initRoutes();
